name: FEATURE-PIPELINE

on:
    pull_request:
        types: ["opened", "reopened", "ready_for_review", "synchronize"]
    workflow_dispatch:

jobs:
    update:
        name: EAS Update
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Restore cache
              id: cache-npm
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-npm-

            - name: Install dependencies
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: npm ci

            - name: Install turbo
              run: npm install turbo --global

            - name: Turbo Cache
              id: turbo-cache
              uses: actions/cache@v3
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Publish update
              id: publish-update
              # Publish app one or app two if it or any of its dependencies changed in the last commit
              run: turbo run publish-update --filter=app-one...[HEAD^1] --filter=app-two...[HEAD^1]  --filter=!@local/ui --cache-dir=.turbo
